import Head from "next/head";
import { SingleToken } from "@components/tokens";

export default function Token() {
  return (
    <>
      <Head>
        <title>SingleToken</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SingleToken />
    </>
  );
}
