import Head from "next/head";
import { Marketplace } from "@components/marketplace";

export default function MarketplacePage() {
  return (
    <>
      <Head>
        <title>Ico Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Marketplace />
    </>
  );
}
