import { CreateIco } from "@components/ico";
import Head from "next/head";

export default function CreateIcoPage() {
  return (
    <>
      <Head>
        <title>Create Ico</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CreateIco />
    </>
  );
}
